<?php
namespace Core\lib;

use Core\BeanFactory;
use Core\init\MyDB;
use \Illuminate\Database\Eloquent\Model;

class Models extends Model
{
    public static function __callStatic($method, $parameters)
    {
        $mydb = clone BeanFactory::getBean(MyDB::class);
        $obj = $mydb->genConnection();
        try{
            return parent::__callStatic($method, $parameters); // TODO: Change the autogenerated stub
        }catch (\Exception $exception){
            return $exception->getMessage();
        }

        finally{
            $mydb->releaseConnection($obj);
        }
    }

}